import { LanguageContent, LanguageCode } from "../types";

export const langPack: Record<LanguageCode, LanguageContent> = {
  ko: {
    langBtn: "English",
    logoTitle: "O2 Top line MIDI",
    logoDesc: "",
    drumTitle: "드럼 미디 업로드",
    drumStatusDefault: "클릭 또는 드래그",
    drumStatusLoaded: "드럼 미디 로드 완료",
    synthTitle: "신스 미디 업로드",
    synthStatusDefault: "클릭 또는 드래그",
    synthStatusLoaded: "신스 미디 로드 완료",
    multitrackTitle: "멀티트랙 미디 업로드",
    multitrackStatusDefault: "클릭 또는 드래그",
    multitrackStatusLoaded: "멀티트랙 미디 로드 완료",
    guideAlert: "스마트 가이드 정보: 미디 분석 결과 파싱 완료!",
    tagGenre: "장르", // used with interpolation e.g., "장르: 힙합"
    tagBpm: "정속 BPM",
    tagScale: "추천 스케일",
    lblMode: "생성 모드 선택",
    btnModeAi: "AI 협업 모드",
    btnModeManual: "AI 끄기 (편집)",
    lblStyle: "보컬 스타일 밀당 (휴지기 & 촘촘함)",
    slLeft: "길게 뽑는 발라드형",
    slMid: "보통",
    slRight: "촘촘한 랩/댄스형",
    lblSeed: "🎲 시드 변주 & 패턴 채우기",
    btnDice: "🎲 주사위 콕콕 (패턴 변주)",
    editorTitle: "탑라인 피아노 롤 에디터",
    restText: "🌬️ 숨통 (Rest)",
    restVocalText: "🌬️ 보컬 프레이징 숨통 (Rest)",
    bottomTip: "팁: 완성된 피아노 탑라인 미디를 다운받아 밴드랩(BandLab)에 던지면 바로 정렬됩니다!",
    btnDownload: "MIDI 다운로드",
    btnDownloadToplineOnly: "탑라인만 내보내기 (.mid)",
    btnDownloadMultiTrack: "멀티트랙 내보내기 (드럼 + 신스 + 탑라인)",
    footerBanner: "🚀 생초보 탈출 파이프라인: 본 앱에서 미디 다운로드 ➡️ BandLab에서 드럼/신스와 합치기 ➡️ Suno AI에 업로드하여 대곡 완성!",
    engineTitle: "🛡️ AI 협업 오토-파일럿 구동 안내 (100% 온디바이스 엔진)",
    engineDetail: "본 앱의 <strong>AI 협업 모드(AI Co-Create)</strong>는 외부 에이전트/LLM 서버 호출이나 별도의 <strong>Gemini API Key를 전혀 요구하지 않는</strong> 로컬 전용 브라우저 구동 엔진입니다. <strong>100% 안전한 로컬 수학적 알고리즘(온디바이스 Markov-chain, 장르별 화성학 매핑 확률 모델)</strong>로 동작하므로 타인의 API 키 누출 우려가 전혀 없으며, 개인 가이드 작업물이 외부 서버로 유출되지 않아 완전히 안전하고 오프라인 상태에서도 100% 무료 구동됩니다.",
    copyright: "© 2026 그런거죠. All Rights Reserved. (🌬️ O2 Production pipeline Standard v0.5)",
    vocalInstrument: "가이드 음색"
  },
  en: {
    langBtn: "한국어",
    logoTitle: "O2 Top line MIDI",
    logoDesc: "",
    drumTitle: "Drum MIDI Upload",
    drumStatusDefault: "Click or drag to upload",
    drumStatusLoaded: "Drum MIDI Loaded",
    synthTitle: "Synth MIDI Upload",
    synthStatusDefault: "Click or drag to upload",
    synthStatusLoaded: "Synth MIDI Loaded",
    multitrackTitle: "Multitrack MIDI Upload",
    multitrackStatusDefault: "Click or drag to upload",
    multitrackStatusLoaded: "Multitrack MIDI Loaded",
    guideAlert: "Smart Guide Info: MIDI analysis parsing complete!",
    tagGenre: "Genre",
    tagBpm: "BPM",
    tagScale: "Recommended",
    lblMode: "Generation Mode",
    btnModeAi: "AI Co-Create",
    btnModeManual: "AI Off (Edit)",
    lblStyle: "Vocal Phrasing (Rest & Density)",
    slLeft: "Long-tone Ballad",
    slMid: "Normal",
    slRight: "Dense Rap/Dance",
    lblSeed: "🎲 Seed Variation & Fill",
    btnDice: "🎲 Roll Dice (Vary Pattern)",
    editorTitle: "Topline Piano Roll Editor",
    restText: "🌬️ Rest",
    restVocalText: "🌬️ Vocal Rest Block",
    bottomTip: "Tip: Download the finished topline MIDI and drag-and-drop it directly into BandLab!",
    btnDownload: "Export MIDI",
    btnDownloadToplineOnly: "Export Topline Only (.mid)",
    btnDownloadMultiTrack: "Export Multi-track (Drums + Synth + Topline)",
    footerBanner: "🚀 Production Pipeline: Download MIDI here ➡️ Merge in BandLab ➡️ Upload to Suno AI to finish your track!",
    engineTitle: "🛡️ AI Co-Create Engine & Safety Guide (100% On-Device Engine)",
    engineDetail: "The <strong>AI Co-Create Mode</strong> in this workstation operates strictly on a <strong>100% on-device mathematical probability model (local Markov-chain and dynamic style algorithms)</strong> running inside your secure web browser. It does not invoke any cloud LLM APIs, and completely bypasses any requirement for a **Gemini API Key** or licensing fees. Your private MIDI files and generated melodies are never transmitted to outside servers, making the production process entirely free, leak-proof, and offline-compatible.",
    copyright: "© 2026 Geureon-geo-jyo ('그런거죠'). All Rights Reserved. (🌬️ O2 Production pipeline Standard v0.5)",
    vocalInstrument: "Vocal Sound"
  }
};
